name: liecasadi

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          channels: conda-forge
          channel-priority: true
      - name: Install dependencies
        run: |
          conda install -y -c conda-forge manifpy
          pip install .[test]
      - name: Test with pytest
        run: |
          pytest
